version: '3.2'

services:
  db:
    image: dockersamples/tidb:nanoserver-1809
    ports:
      - "3306:4000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: awesome-api
    environment:
      - "Data:Provider=MySQL"
      - "Data:ConnectionString=Server=db;Port=4000;Database=AlbumViewer;User=root;SslMode=None"
    ports:
      - '8090:80'

networks:
  default:
    external:
      name: nat