apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-deployment
  template:
    metadata:
      labels:
        app: kubernetes-demo-deployment
    spec:
      containers:
      - name: kubernetes-demo-application
        image: docker-compose_web
        ports:
          - containerPort: 4000